// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// compress_file
int compress_file(const std::string& in_file, const int& compress);
RcppExport SEXP _RhtslibTest_compress_file(SEXP in_fileSEXP, SEXP compressSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type in_file(in_fileSEXP);
    Rcpp::traits::input_parameter< const int& >::type compress(compressSEXP);
    rcpp_result_gen = Rcpp::wrap(compress_file(in_file, compress));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_RhtslibTest_compress_file", (DL_FUNC) &_RhtslibTest_compress_file, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_RhtslibTest(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
